# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /aisp/account-consents/{consentId}_get for http method type GET 
# RoostTestHash=6f5dabe09d
# 
# 

# ********RoostGPT********
Feature: RESTful API for /aisp/account-consents/{consentId} endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = 'Bearer ' + authToken

  Scenario Outline: Get account consent details with valid consentId and expected status code 200
    Given url urlBase + '/aisp/account-consents/<consentId>'
    And header x-fapi-auth-date = '<x-fapi-auth-date>'
    And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
    And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
    And header Accept-Language = '<Accept-Language>'
    When method get
    Then status 200
    And match response contains { consentId: '#string', status: '#string', permissions: '#array' }
    And match response.links contains { self: '#string' }

    Examples:
      | read('aisp_account-consents_consentId_get.csv') |

  Scenario: Get account consent details with invalid consentId and expect status code 400
    Given url urlBase + '/aisp/account-consents/invalid'
    When method get
    Then status 400
    And match response contains { id: '#string', errors: '#array' }

  Scenario: Get account consent details with missing Authorization header and expect status code 401
    Given url urlBase + '/aisp/account-consents/consent123'
    And header Authorization = ''
    When method get
    Then status 401

  Scenario: Get account consent details with unsupported Accept-Language and expect status code 406
    Given url urlBase + '/aisp/account-consents/consent123'
    And header Accept-Language = 'unsupported-language'
    When method get
    Then status 406

  Scenario: Get account consent details and expect status code 429 when too many requests
    Given url urlBase + '/aisp/account-consents/consent123'
    When method get
    Then status 429
    And match responseHeaders contains { 'Retry-After': '#integer' }

  Scenario: Get account consent details and expect status code 500 on server error
    Given url urlBase + '/aisp/account-consents/consent123'
    When method get
    Then status 500
    And match response contains { id: '#string', errors: '#array' }

  Scenario: Get account consent details and expect status code 503 on service unavailable
    Given url urlBase + '/aisp/account-consents/consent123'
    When method get
    Then status 503

  Scenario: Get account consent details and expect status code 504 on gateway timeout
    Given url urlBase + '/aisp/account-consents/consent123'
    When method get
    Then status 504
