# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /aisp/account-consents_post for http method type POST 
# RoostTestHash=923406b6e1
# 
# 

# ********RoostGPT********
Feature: Account Consents API Feature

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * url urlBase
    * def authHeader = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }
    * header Authorization = karate.properties['AUTH_TOKEN']

  Scenario Outline: Create a new account consent with valid parameters
    Given path '/aisp/account-consents'
    And request <requestBody>
    And header Authorization = authHeader.Authorization
    And header Content-Type = 'application/json'
    When method post
    Then status 201
    And match response ==
      """
      {
        "data": {
          "consentId": "#string",
          "creationDate": "#string",
          "status": "#string",
          "statusUpdateDate": "#string",
          "permissions": "#array",
          "expirationDate": "#string",
          "transactionFromDate": "#string",
          "transactionToDate": "#string"
        },
        "links": {
          "self": "#string",
          "prev": "#string",
          "next": "#string"
        }
      }
      """
    And match header 'x-fapi-interaction-id' == '#string'

    Examples:
      | read('aisp_account-consents_post.csv') |

  Scenario Outline: Create a new account consent with invalid parameters
    Given path '/aisp/account-consents'
    And request <requestBody>
    And header Authorization = authHeader.Authorization
    And header Content-Type = 'application/json'
    When method post
    Then status 400
    And match response ==
      """
      {
        "id": "#string",
        "errors": [
          {
            "code": "#string",
            "causes": "#string",
            "extendedDetails": "#object"
          }
        ]
      }
      """
    And match header 'x-fapi-interaction-id' == '#string'

    Examples:
      | read('aisp_account-consents_post.csv') |
